name: Terraform Plan

on:
  push: 
     branches:
      - main
     paths:
      - '**.tf'
      
      

jobs:
  detect-changed-dirs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Allows comparison with previous commit

      - name: Set base commit
        id: set-base
        run: |
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            echo "BASE=$(git rev-parse HEAD~1)" >> $GITHUB_ENV
          else
            echo "BASE=$(git rev-parse HEAD)" >> $GITHUB_ENV
          fi

      - name: Find Changed Terraform Directories
        id: set-matrix
        run: |
          echo "Detecting changed .tf file directories..."
          dirs=$(git diff --name-only $BASE HEAD | grep '\.tf$' | xargs -n1 dirname | sort -u | jq -R . | jq -s .)
          if [[ "$dirs" == "[]" ]]; then
            # Fallback dummy to avoid matrix error
            echo "No changed .tf directories. Setting dummy path."
            dirs='["terraform/dummy"]'
          fi
          echo "Found dirs: $dirs"
          echo "matrix={\"dir\": $dirs}" >> $GITHUB_OUTPUT

  terraform-plan:
    needs: detect-changed-dirs
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.detect-changed-dirs.outputs.matrix) }}
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - name: Skip dummy
        if: ${{ matrix.dir == 'terraform/dummy' }}
        run: echo "No Terraform changes to plan. Skipping."

      - name: Checkout code
        if: ${{ matrix.dir != 'terraform/dummy' }}
        uses: actions/checkout@v3

      - name: Setup Terraform
        if: ${{ matrix.dir != 'terraform/dummy' }}
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        if: ${{ matrix.dir != 'terraform/dummy' }}
        run: terraform init

      - name: Terraform Format Check
        if: ${{ matrix.dir != 'terraform/dummy' }}
        run: terraform fmt -check

      - name: Terraform Plan
        if: ${{ matrix.dir != 'terraform/dummy' }}
        run: terraform plan
