name: terraform plan
on:
  push:
    branches: [Develop]
jobs:
  terraform-plan:
    name: terraform plan
    runs-on: ubuntu-latest
    steps:
      -name: Checkout code
       uses: actions/checkout@v4

      -name: Setup Terraform
       uses: hashicorp/setup-terraform@v3

      -name: Terraform Init
       uses: terraform init

      -name: Terraform Format Check
       uses: terraform fmt -check

      -name: Terraform Plan
       uses: terraform plan -out=tfplan

      -name: Save Terraform Plan As Artifact
       uses: actions/upload-artifact@v4
       with:
         name: tfplan
         path: tfplan


       
      
