name: Terraform Init & Plan (Changed Directories Only)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Init & Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures git history is available for diff

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # change as needed


      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Find changed Terraform directories
        id: find_dirs
        run: |
          echo "Searching for changed directories with .tf files..."

          # Get previous commit SHA, fallback for first commit
          base_ref=$(git rev-parse HEAD^ || echo "")
          if [ -z "$base_ref" ]; then
            echo "First commit, scanning all .tf directories"
            find . -type f -name "*.tf" -exec dirname {} \; | sort -u > tf_dirs.txt
          else
            git diff --name-only $base_ref HEAD | grep '\.tf$' | xargs -r -n1 dirname | sort -u > tf_dirs.txt
          fi

          echo "Terraform directories to process:"
          cat tf_dirs.txt || echo "None"

      - name: Run Terraform Init & Plan in changed directories
        run: |
          if [ ! -s tf_dirs.txt ]; then
            echo "No changed Terraform directories found. Skipping."
            exit 0
          fi

          while read dir; do
            echo "============================="
            echo "Processing: $dir"
            echo "============================="
            cd "$dir"

            terraform init -input=false
            terraform plan -input=false || echo "Terraform plan failed in $dir"

            cd - > /dev/null
          done < tf_dirs.txt
