name: Terraform Auto Init & Plan

on:
  push:
    branches:
      - main  # or any branch you want
  workflow_dispatch:  # optional: manual trigger from GitHub UI

jobs:
  terraform:
    name: Terraform Init and Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # change as needed

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0  # set your preferred version

      - name: Find Terraform directories
        id: find_dirs
        run: |
          echo "Scanning for Terraform directories..."
          dirs=$(find . -type f -name "*.tf" -exec dirname {} \; | sort -u)
          echo "$dirs" > tf_dirs.txt
          echo "Found directories:"
          cat tf_dirs.txt

      - name: Terraform Init & Plan in each directory
        run: |
          while read dir; do
            echo "============================="
            echo "Processing: $dir"
            echo "============================="
            cd "$dir"

            terraform init -input=false
            terraform plan -input=false || echo "Terraform plan failed in $dir"

            cd - > /dev/null
          done < tf_dirs.txt
