name: Terraform Plan (Dynamic Recursive)

on:
  push:
    branches: [main]

jobs:
  detect-changed-dirs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Find All Changed Terraform Directories
        id: set-matrix
        run: |
          echo "Detecting changed .tf file directories..."
          changed_dirs=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} \
            | grep '\.tf$' \
            | xargs -n1 dirname \
            | sort -u)

          if [ -z "$changed_dirs" ]; then
            echo "No changed Terraform directories."
            echo 'matrix={"dir":[]}' >> $GITHUB_OUTPUT
          else
            matrix_json=$(echo "$changed_dirs" | jq -R . | jq -s .)
            echo "matrix={\"dir\":$matrix_json}" >> $GITHUB_OUTPUT
            echo "Found directories: $matrix_json"
          fi

  terraform-plan:
    name: Terraform Plan
    needs: detect-changed-dirs
    if: needs.detect-changed-dirs.outputs.matrix != '{"dir":[]}'
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.detect-changed-dirs.outputs.matrix) }}
    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
