name: Terraform Plan

on:
  push:
    branches:
      - main  # or your working branch

jobs:
  detect-changed-dirs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set base commit
        id: base
        run: echo "BASE=$(git rev-parse HEAD^1)" >> $GITHUB_ENV

      - name: Find Changed Terraform Directories
        id: set-matrix
        run: |
          echo "Detecting changed .tf file directories..."
          dirs=$(git diff --name-only $BASE HEAD | grep '\.tf$' | xargs -n1 dirname | sort -u)

          if [[ -z "$dirs" ]]; then
            echo "No .tf changes found. Using dummy fallback."
            echo 'matrix={"dir": ["__no_changes__"]}' >> $GITHUB_OUTPUT
          else
            json=$(printf '%s\n' $dirs | jq -R . | jq -s '{dir: .}')
            echo "Found dirs: $json"
            echo "matrix=$json" >> $GITHUB_OUTPUT
          fi

  terraform-plan:
    needs: detect-changed-dirs
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.detect-changed-dirs.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Skip - No changes to .tf files
        if: ${{ matrix.dir == '__no_changes__' }}
        run: echo "No Terraform changes detected. Skipping."

      - name: Setup Terraform
        if: ${{ matrix.dir != '__no_changes__' }}
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        if: ${{ matrix.dir != '__no_changes__' }}
        run: terraform init
        working-directory: ${{ matrix.dir }}

      - name: Terraform Format Check
        if: ${{ matrix.dir != '__no_changes__' }}
        run: terraform fmt -check
        working-directory: ${{ matrix.dir }}

      - name: Terraform Plan
        if: ${{ matrix.dir != '__no_changes__' }}
        run: terraform plan
        working-directory: ${{ matrix.dir }}
