name: Terraform Init & Plan (Always Run)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Init & Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # change as needed


      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0  # or your required version

      - name: Find all Terraform directories
        id: find_dirs
        run: |
          echo "Searching for all directories with .tf files..."
          find . -type f -name "*.tf" -exec dirname {} \; | sort -u > tf_dirs.txt
          echo "Terraform directories found:"
          cat tf_dirs.txt

      - name: Run Terraform Init & Plan in all directories
        run: |
          while read dir; do
            echo "============================="
            echo "Processing: $dir"
            echo "============================="
            cd "$dir"

            terraform init -input=false
            terraform plan -input=false || echo "Terraform plan failed in $dir"

            cd - > /dev/null
          done < tf_dirs.txt
