name: Terraform Plan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  detect-changed-dirs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Find Changed Terraform Directories
        id: set-matrix
        run: |
          echo "Detecting changed .tf file directories..."
          CHANGED_DIRS=$(git diff --name-only HEAD^ HEAD | grep '\.tf$' | xargs -n1 dirname | sort -u | uniq)
          
          DIRS_JSON=$(jq -n --argjson dirs "$(printf '%s\n' $CHANGED_DIRS | jq -R . | jq -s .)" '{dir: $dirs}')
          
          echo "matrix=$DIRS_JSON" >> $GITHUB_OUTPUT
          echo "Found dirs: $DIRS_JSON"

  terraform-plan:
    needs: detect-changed-dirs
    if: ${{ fromJson(needs.detect-changed-dirs.outputs.matrix).dir != '' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.detect-changed-dirs.outputs.matrix) }}
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan
