name: Terraform Plan

on:
  push:
    branches:
      - main
  

jobs:
  detect-changed-dirs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set base commit
        id: base
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "BASE=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV
          else
            # fallback to 1 previous commit if `before` is empty
            BASE=$(git rev-parse HEAD~1)
            echo "BASE=$BASE" >> $GITHUB_ENV
          fi

      - name: Find Changed Terraform Directories
        id: set-matrix
        run: |
          echo "Detecting changed .tf file directories..."

          CHANGED_DIRS=$(git diff --name-only $BASE HEAD | grep '\.tf$' | xargs -n1 dirname | sort -u)

          if [ -z "$CHANGED_DIRS" ]; then
            echo "No .tf file changes found. Using dummy."
            echo '{"dir":["terraform/dummy"]}' > dirs.json
          else
            echo "$CHANGED_DIRS" | jq -R . | jq -s '{dir: .}' > dirs.json
          fi

          echo "Directories to run plan:"
          cat dirs.json
          echo "matrix=$(cat dirs.json)" >> $GITHUB_OUTPUT

  terraform-plan:
    needs: detect-changed-dirs
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.detect-changed-dirs.outputs.matrix) }}
    continue-on-error: true
    name: Terraform Plan (${{ matrix.dir }})
    steps:
      - name: Skip dummy
        if: ${{ matrix.dir == 'terraform/dummy' }}
        run: echo "No Terraform changes to plan. Skipping."

      - name: Checkout code
        if: ${{ matrix.dir != 'terraform/dummy' }}
        uses: actions/checkout@v4

      - name: Setup Terraform
        if: ${{ matrix.dir != 'terraform/dummy' }}
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        if: ${{ matrix.dir != 'terraform/dummy' }}
        run: terraform init
        working-directory: ${{ matrix.dir }}

      - name: Terraform Format Check
        if: ${{ matrix.dir != 'terraform/dummy' }}
        run: terraform fmt -check
        working-directory: ${{ matrix.dir }}

      - name: Terraform Plan
        if: ${{ matrix.dir != 'terraform/dummy' }}
        run: terraform plan
        working-directory: ${{ matrix.dir }}
