name: Terraform Plan (Only on Changed Directories)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Changed Directories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # change as needed



      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Get changed directories with .tf files
        id: changes
        run: |
          echo "Finding changed .tf files..."
          changed_dirs=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.tf$' | xargs -r -n1 dirname | sort -u)
          
          if [ -z "$changed_dirs" ]; then
            echo "No Terraform file changes detected."
            echo "changed_dirs=" >> "$GITHUB_ENV"
            exit 0
          fi

          echo "$changed_dirs" > changed_tf_dirs.txt
          echo "Changed directories with .tf files:"
          cat changed_tf_dirs.txt
          echo "changed_dirs=$(cat changed_tf_dirs.txt | paste -sd "," -)" >> "$GITHUB_ENV"

      - name: Terraform Init & Plan in Changed Directories
        if: env.changed_dirs != ''
        run: |
          while read dir; do
            echo "============================="
            echo "Processing: $dir"
            echo "============================="
            cd "$dir"

            terraform init -input=false
            terraform plan -input=false || echo "Terraform plan failed in $dir"

            cd - > /dev/null
          done < changed_tf_dirs.txt
