name: terraform plan

on:
  push:
    branches: [main]

jobs:
  terraform-plan:
    name: terraform plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Save Terraform Plan As Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan
